name: pre-commit

permissions: {} # none

on:
  pull_request:
  push:
    branches: [master]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: prek
      uses: j178/prek-action@e98a699c41eb69ab013a45817a0406469a748f8d # v2.0.5
      with:
        prek-version: '0.4.9'
